name = "portfolio-feature-flags"
main = "workers/feature-flags/src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "FEATURE_FLAGS_KV"
id = "55a586e168e54566bcfb0a1e6dd11f88"
preview_id = "790d0a984ac748aaae24cba1038901cb"

[vars]
ALLOWED_ORIGINS = "https://tylerearls.com,http://localhost:3000,http://localhost:4173"

[observability]
enabled = true
